apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcert
  namespace: kcert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcert
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcert
subjects:
- kind: ServiceAccount
  name: kcert
  namespace: kcert
roleRef:
  kind: ClusterRole
  name: kcert
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kcert
  namespace: kcert
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  resourceNames: ["kcert"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kcert
  namespace: kcert
subjects:
- kind: ServiceAccount
  name: kcert
  namespace: kcert
roleRef:
  kind: ClusterRole
  name: kcert
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcert
  namespace: kcert
  labels:
    app: kcert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcert
  template:
    metadata:
      labels:
        app: kcert
    spec:
      serviceAccountName: kcert
      containers:
      - name: kcert
        image: nabsul/kcert:v1.0.0
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ACME__DIRURL
          value: # set this to "https://acme-staging-v02.api.letsencrypt.org/directory" or "" (you probably want the second one)
        - name: ACME__TERMSACCEPTED
          value: # You must set this to "true" to indicate that you have read and accepted Let's Encrypt's TOS: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
        - name: ACME__EMAIL
          value: # This should be the email that Let's Encrypt contacts about your certificate
        - name: ACME__KEY
          valueFrom:
            secretKeyRef:
              - name: kcert
                key: acme
        # I you don't want to set up email notifications, you can delete all the "SMTP__" settings here.
        - name: SMTP__EMAILFROM
          value: # The address from which KCert will send you notifications
        - name: SMTP__HOST
          value: # Host name of your SMTP server
        - name: SMTP__PORT
          value: # Port of your SMTP server (be sure to put quotes around the port number)
        - name: SMTP__USER
          value: # SMTP Username
        - name: SMTP__PASS
          fromValue:
            secretKeyRef:
              - name: kcert
                key: smtp
---
apiVersion: v1
kind: Service
metadata:
  name: kcert
  namespace: kcert
  labels:
    app: kcert
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: kcert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kcert
  namespace: kcert
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /.well-known/acme-challenge
        pathType: Prefix
        backend:
          service:
            name: kcert
            port:
              number: 80
