apiVersion: v1
kind: Namespace
metadata:
  name: kcert
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcert
  namespace: kcert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcert
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets", "services"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcert
subjects:
- kind: ServiceAccount
  name: kcert
  namespace: kcert
roleRef:
  kind: ClusterRole
  name: kcert
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcert
  namespace: kcert
data:
  appsettings.prod.yaml: |
    {
      "EnableAutoRenew": __true|false__,
      "Acme": {
        "DirUrl": __"https://acme-staging-v02.api.letsencrypt.org/directory"|"https://acme-v02.api.letsencrypt.org/directory"__,
        "TermsAccepted": __true|false__,
        "Email": __EMAIL__
      },
      "Smtp": {
        "EmailFrom": __EMAIL__,
        "Host": __HOST__,
        "Port": __000__,
        "User": __SMTP_USER_NAME__
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcert
  namespace: kcert
  labels:
    app: kcert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcert
  template:
    metadata:
      labels:
        app: kcert
    spec:
      serviceAccountName: kcert
      volumes:
      - name: kcert
        configMap:
          name: kcert
      containers:
      - name: kcert
        image: nabsul/kcert:v1.0.0
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: NAMESPACE
          value: kcert
        - name
---
apiVersion: v1
kind: Service
metadata:
  name: kcert
  namespace: kcert
  labels:
    app: kcert
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: kcert
