apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "names.serviceAccount is required" .Values.names.serviceAccount }}
  namespace: {{ required "names.namespace is required" .Values.names.namespace }}
