apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ required "names.clusterRoleBinding is required" .Values.names.clusterRoleBinding }}
subjects:
- kind: ServiceAccount
  name: {{ required "names.serviceAccount is required" .Values.names.serviceAccount }}
  namespace: {{ required "names.namespace is required" .Values.names.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ required "names.clusterRole is required" .Values.names.clusterRole }}
  apiGroup: rbac.authorization.k8s.io
