apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ required "names.role is required" .Values.names.role }}
  namespace: {{ required "names.namespace is required" .Values.names.namespace }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
