{{ if !.Values.allowedNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcert.fullname" . }}
{{- if .Values.forHelm }}
  labels:
    {{- include "kcert.labels" . | nindent 4 }}
{{- end }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
{{ else }}
{{- range $index, $value := .Values.allowedNamespaces }}
{{- if ne $index 0 }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kcert.fullname" . }}
  namespace: {{ $value }}
{{- if .Values.forHelm }}
  labels:
    {{- include "kcert.labels" . | nindent 4 }}
{{- end }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
{{- end }}
{{ end }}
