apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kcert.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
{{- if .Values.forHelm }}
  labels:
    {{- include "kcert.labels" . | nindent 4 }}
{{- end }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
