apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "kcert.labels" . | nindent 4 }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
