apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "kcert.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name | quote }}
  namespace: {{ .Release.Namespace | default "default" }}
roleRef:
  kind: Role
  name: {{ .Values.name | quote }}
  apiGroup: rbac.authorization.k8s.io
