apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kcert.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
{{- if .Values.forHelm }}
  labels:
    {{- include "kcert.labels" . | nindent 4 }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "kcert.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
roleRef:
  kind: Role
  name: {{ include "kcert.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
