{{- if .Values.smtp.host }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kcert.fullname" . }}-smtp
  namespace: {{ .Release.Namespace | default "default" }}
{{- if .Values.forHelm }}
  labels:
    {{- include "kcert.labels" . | nindent 4 }}
{{- end }}
stringData:
    password: {{ required "smtp.pass is required" .Values.smtp.pass }}
{{- end }}
