apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcert.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ include "kcert.fullname" . }}
    {{- if .Values.forHelm }}
    {{- include "kcert.labels" . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-admin
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{ include "kcert.fullname" . }}
    {{- if .Values.forHelm }}
    {{- include "kcert.selectorLabels" . | nindent 4 }}
    {{- end }}
