set shell := ['pwsh', '-NoLogo', '-NoProfile', '-Command']

create_vm:
    #!pwsh
    $sshKey = (doctl compute ssh-key list --no-header --format ID,Name | where {$_.Contains('dummy')}).Split(' ')[0]
    $imageId =  (doctl compute image list --no-header --format ID,Name | where {$_.Contains('Talos')}).Split(' ')[0]
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $vmName = "kcert-test-$timestamp"
    op run -- doctl compute droplet create --region sfo3 --image $imageId --size s-2vcpu-4gb --enable-private-networking --ssh-keys $sshKey $vmName

list_vms:
    #!pwsh
    doctl compute droplet list

delete_vm vm_id:
    #!pwsh
    - doctl compute droplet delete {{vm_id}} --force

init vm_ip:
    #!pwsh
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $cfgDir = "kcert-test-$timestamp"
    $talosconfig = "$cfgDir/talosconfig"
    $controlplane = "$cfgDir/controlplane.yaml"
    mkdir $cfgDir | Out-Null
    talosctl gen config $cfgDir https://{{vm_ip}}:6443 --additional-sans {{vm_ip}} -o $cfgDir
    talosctl --talosconfig $talosconfig config endpoint {{vm_ip}}
    talosctl --talosconfig $talosconfig config node {{vm_ip}}
    $yaml = Get-Content -Path $controlplane
    $yaml = $yaml -replace '# allowSchedulingOnControlPlanes:', 'allowSchedulingOnControlPlanes:'
    Set-Content -Path $controlplane -Value $yaml
    talosctl --talosconfig $talosconfig apply-config --insecure --nodes {{vm_ip}} --file $controlplane
    echo "Sleeping for 10 seconds to allow the node to initialize..."
    Start-Sleep -Seconds 10
    talosctl --talosconfig $talosconfig bootstrap
    echo "Sleeping for 10 seconds to allow the cluster to stabilize..."
    Start-Sleep -Seconds 10
    talosctl --talosconfig $talosconfig health
    talosctl --talosconfig $talosconfig kubeconfig $cfgDir

setup_cluster dir:
    kubectl --kubeconfig .\{{dir}}\kubeconfig apply -f .\nginx-namespace.yaml
    helm --kubeconfig .\{{dir}}\kubeconfig install nginx-ingress ingress-nginx/ingress-nginx --namespace ingress-nginx --set controller.kind=DaemonSet --set controller.hostPort.enabled=true --set controller.hostPort.ports.http=80 --set controller.hostPort.ports.https=443
    kubectl --kubeconfig .\{{dir}}\kubeconfig apply -f .\kcert-test-svc.yaml

save-configs dir_name:
    #!pwsh
    cd {{dir_name}}
    tar czvf {{dir_name}}.tgz .
    op document create {{dir_name}}.tgz --vault kcert

download-configs dir_name:
    #!pwsh
    op document get {{dir_name}}.tgz --vault nblspace --output {{dir_name}}.tgz
    mkdir {{dir_name}} | Out-Null
    tar xzvf {{dir_name}}.tgz -C {{dir_name}}
    rm {{dir_name}}.tgz
