apiVersion: v2
name: kcert-configmap
description: Deploys a configmap for KCert to consume and create a cert
version: 1.0.0
appVersion: 1.1.0
maintainers:
- name: Nabeel Sulieman
  url: https://nabeel.dev
keywords:
- kubernetes
- letsencrypt
- ssl
sources:
 - https://github.com/nabsul/kcert
